# Generated by Django 2.2.3 on 2019-08-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_categoria_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Contas',
        ),
    ]
