# Generated by Django 2.2.3 on 2019-08-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20190801_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contas',
            new_name='Categoria',
        ),
    ]
