# Generated by Django 2.2.3 on 2019-08-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_auto_20190801_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
